Uni v3
covalenthq/goldrush-decoder pull request #20
Opened 2024-02-21 20:04 UTC by gurjotd23

Decoded the following Contracts and events for Uniswap V3 on ethereum:

Factory Contract:
- Pair Created

Pair Contract:
- Mint
- Burn
- Flash Loan
- Swap
- Collect Fees

NFT Positions Manager:
- Increase Liquidity
- Decrease Liquidity
- Collect Fees

2024-02-22 20:00 UTC, jagnani73 requested changes

2024-02-22 20:03 UTC, gurjotd23 commented on package.json
> +        "config": "^3.3.11",
IDK this file even changed tbh

2024-02-22 20:11 UTC, gurjotd23 commented on services/decoder/protocols/uniswap-v3/uniswap-v3.decoders.ts
> +                ticker_symbol: Token1?.[0].contract_ticker_symbol,
fixed

2024-02-22 20:13 UTC, gurjotd23 commented on services/decoder/protocols/uniswap-v3/uniswap-v3.decoders.ts
> +            },
So in this, the heading of amount, amount0, amount1, sender & owner should be capitalized, but tickUpper and tickLower can remain the same?

2024-02-22 20:13 UTC, gurjotd23 commented on services/decoder/protocols/uniswap-v2/uniswap-v2.configs.ts
> +    },
anything to do for this in this PR for now?

2024-02-23 05:54 UTC, jagnani73 commented on services/decoder/protocols/uniswap-v2/uniswap-v2.configs.ts
> +    },
No no, just confirming a blocker

2024-02-23 05:55 UTC, jagnani73 commented on services/decoder/protocols/uniswap-v3/uniswap-v3.decoders.ts
> +            },
Why? tickLower can be Tick Lower

2024-02-23 16:38 UTC, jagnani73 approved these changes

2024-02-24 01:26 UTC, merged